# Generated by Django 3.0 on 2019-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='object',
        ),
        migrations.AddField(
            model_name='room',
            name='object_any',
            field=models.BooleanField(default=False, verbose_name='何でもよい'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_art',
            field=models.BooleanField(default=False, verbose_name='美術館・博物館'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_bath',
            field=models.BooleanField(default=False, verbose_name='温泉'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_gourmet',
            field=models.BooleanField(default=False, verbose_name='グルメ'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_historic',
            field=models.BooleanField(default=False, verbose_name='歴史・文化的遺産'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_nature',
            field=models.BooleanField(default=False, verbose_name='自然や景勝地'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_other',
            field=models.BooleanField(default=False, verbose_name='その他'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_shopping',
            field=models.BooleanField(default=False, verbose_name='ショッピング'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_sport',
            field=models.BooleanField(default=False, verbose_name='スポーツ・アクティビティ'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_zoo_aquarium',
            field=models.BooleanField(default=False, verbose_name='動物園・水族館'),
        ),
    ]
