# Generated by Django 3.0 on 2019-12-14 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_auto_20191214_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
