# Generated by Django 3.0 on 2019-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20191214_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
