<<<<<<< HEAD
# Generated by Django 3.0 on 2019-12-15 05:44
=======
# Generated by Django 3.0 on 2019-12-15 04:59
>>>>>>> 138e5a0aa31e0468ef47b4b8992bfab70f24a196

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20191214_1853'),
        ('room', '0005_room_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='place',
            field=models.ManyToManyField(blank=True, to='place.Place'),
        ),
    ]
