# Generated by Django 3.0 on 2019-12-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('min_time', models.PositiveIntegerField()),
                ('max_time', models.PositiveIntegerField()),
                ('min_cost', models.PositiveIntegerField()),
                ('max_cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(choices=[('grume', 'Gourmet food')], max_length=5)),
                ('mood', models.CharField(choices=[('slow', 'Slow'), ('high', 'High')], max_length=4)),
                ('option', models.TextField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
            ],
        ),
    ]
