# Generated by Django 3.0 on 2019-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20191214_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
