# Generated by Django 3.0 on 2019-12-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '女性'), ('2', '男性'), ('3', 'その他')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
